### PR TITLE
Session2

### PR DESCRIPTION
**Pull request by denzalman**

### CODE REVIEW

**Comment by denzalman** [comment]
2. for overflow error you have to make loop with indexes... and it will make code less readable
3. my variant works too and works good.
4. why do you think so? i did exactly the same report like in assignment
5. it convert parameter from TODAY+N to integer number.
6. my variant works too.... but i will check click.option variant

**Comment by cubann** [comment]
https://github.com/ops-school/opsschool3-coding/blob/09501e96b5b3f6d7e67e4547c5478798a39c4657/home-assignments/session2/exercise1.txt#L39

**Comment by denzalman** [comment]
ok, missed it... but with date format more interesting :)

**Comment by cubann** [comment]
>     1. for overflow error you have to make loop with indexes... and it will make code less readable
> 
Why you can not raise an exception if user entered number bigger than 9 ? and catch in except?

**Comment by cubann** [comment]
> my variant works too.... but i will check click.option variant
> 
I did not say that it does not work I thought that to user more descriptive tag it will more convenient , for eg. what is -f -c ? but I will use smth like --degrees <> than for me it is more understandable what to write there

**Comment by cubann** [comment]
> it convert parameter from TODAY+N to integer number.
Why to convert at all if you use default int value and loop from it

**Comment by cubann** [comment]
python3.6 cli.py --city dublin
gives me :

> The weather in Dublin today is Rain with temperatures trailing from 7-11 celsius.
> 
> Forecast for the next 0 days: 

It is better not to print at all "Forecast for the next 0 days:' if it is only one day , isn't it?

**Comment by cubann** [comment]
python3.6 cli.py --city dublin -c -f
gives:

> The weather in Dublin today is Rain with temperatures trailing from 45-53 fahrenheit.
> 
> Forecast for the next 0 days: 

Is it wrong that you printed result in Fahrenheit ? is it right? why can I  at all use to options?

**Pull request closed without merging**
